name: SlimefunInfiniteBlocks
version: ${project.version}
main: net.touruya.infiniteblock.implementation.InfiniteBlocks
api-version: 1.20
depend:
  - Slimefun
description: 无限方块
authors:
  - TouRuya
  - balugaq
commands:
  sibstorage:
    aliases:
      - slimefuninfiniteblockstorage
  sibstar:
    aliases:
      - slimefuninfiniteblockstar

permissions:
  slimefuninfiniteblock.admin:
    description: Allows you to use all SFWorldedit commands
    default: op
  slimefuninfiniteblock.command.admin:
    description: Allows you to use all the SFWorldedit commands
    default: op
  slimefuninfiniteblock.command.storage:
    description: Allows you to use the /sibstorage command
    default: op
  slimefuninfiniteblock.command.star:
    description: Allows you to use the /sibstar command
    default: op
